Simir.WebInterfaceComAuth/Areas/Configuracao/Controllers/AterroController.cs
using Simir.Application.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Simir.CrossCutting.Security;
using Simir.Application.Interfaces;
using Simir.WebInterfaceComAuth.Filters;
using Simir.WebInterfaceComAuth.Helpers;
using Simir.Domain.Enuns;

namespace Simir.WebInterfaceComAuth.Areas.Configuracao.Controllers
{
    public class AterroController : Controller
    {

        private readonly IAterroApp _Aterro;
        private readonly IEnderecoApp _enderecoApp;

        public AterroController(IAterroApp Aterro,
            IEnderecoApp enderecoApp)
        {
            _Aterro = Aterro;
            _enderecoApp = enderecoApp;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Configuracao/Aterro
        [MenuAuthorize]
        public async Task<ActionResult> Index(int? id)
        {
            int prefeituraID = User.Identity.GetPrefeituraID();

            return View(_Aterro.getAterro(id, prefeituraID));
        }
        public async Task<ActionResult> Aterros()
        {
            int prefeituraID = User.Identity.GetPrefeituraID();
            var tiposFake = _Aterro.GetAllAterros(prefeituraID);
            return Json(tiposFake, JsonRequestBehavior.AllowGet);
        }

        [MenuAuthorize(Action = "Index")]
        public async Task<ActionResult> BuscaProgramacao()
        {
            int prefeituraID = User.Identity.GetPrefeituraID();

            return PartialView(_Aterro.BuscaProgramacao(prefeituraID));
        }
        [HttpPost]
        [MultiplosBotoes(Variavel = "Btn", Valor = "Novo")]
        public async Task<ActionResult> Novo(AterroVM model)
        {

            return RedirectToAction("Index", new { id = "" });

        }
        [HttpPost]
        [MenuAuthorize(Action = "Index")]
        [MultiplosBotoesAttribute(Variavel = "Btn", Valor = "Salvar")]
        public async Task<ActionResult> Salvar(AterroVM model)
        {
            var userId = User.Identity.GetUserId();
            var user = await UserManager.FindByIdAsync(userId);
            int prefeituraID = (int)(user.TBUsuario.PrefeituraID);
            model.PrefeituraID = prefeituraID;

            var bAlterar = User.Identity.TemPermicao(TipoPermissao.Alterar);
            var bIncluir = User.Identity.TemPermicao(TipoPermissao.Incluir);

            if (!(bAlterar) && (model.AterroID != 0))
            {
                TempData["Avis.Permicao"] = "Você não possui permissão para alterar a operação!";
                return View("Index", model);
            }
            if (!(bIncluir) && (model.AterroID == 0))
            {
                TempData["Avis.Permicao"] = "Você não possui permissão para incluir uma nova operação!";
                return View("Index", model);
            }

            if (ModelState.IsValid)
            {
                var result = await _Aterro.SalvarProgramacao(user, model);
                if (!result.Any())
                {
                    TempData["Avis.Salvar"] = "Programação salva com sucesso!";
                    return RedirectToAction("Index", new { id = "" });
                }
                foreach (var item in result)
                {
                    if (ModelState.ContainsKey(item.Key))
                    {
                        ModelState[item.Key] = item.Value;
                    }
                    else
                    {
                        ModelState.Add(item);
                    }
                }
            }

            return View("Index", model);
        }
        [HttpPost]
        [MenuAuthorize(Action = "Index")]
        [MultiplosBotoesAttribute(Variavel = "Btn", Valor = "Excluir")]
        public async Task<ActionResult> Excluir(AterroVM model)
        {
            var userId = User.Identity.GetUserId();
            var user = await UserManager.FindByIdAsync(userId);
            int prefeituraID = (int)(user.TBUsuario.PrefeituraID);

            var bExcluir = User.Identity.TemPermicao(TipoPermissao.Excluir);


            if (!(bExcluir))
            {
                TempData["Avis.Permicao"] = "Você não possui permissão para excluir a operação!";
                return View("Index", model);
            }


            var result = await _Aterro.ExcluirProgramacao(user, model.AterroID);


            if (!result.Any())
            {
                TempData["Avis.Excluir"] = "Programação excluida com sucesso!";
                return RedirectToAction("Index", new { id = "" });
            }
            foreach (var item in result)
            {
                if (ModelState.ContainsKey(item.Key))
                {
                    ModelState[item.Key] = item.Value;
                }
                else
                {
                    ModelState.Add(item);
                }
            }

            return View("Index", model);
        }
    }
}

Simir.WebInterfaceComAuth/Areas/Configuracao/Views/Aterro/BuscaProgramacao.cshtml
@model IList<Simir.Application.ViewModels.AterroCadastradosVM>


<table id="example" class="table table-hover" cellspacing="0">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().nmFantasia)</th>
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().CNPJ)</th>
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().bAterroControlado)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                <td>
                    @Html.DisplayFor(item => item[i].nmFantasia)
                </td>
                <td>
                    @Html.DisplayFor(item => item[i].CNPJ)
                </td>
                <td>
                    @Html.DisplayFor(item => item[i].bAterroControlado)
                </td>
                <td>
                    <a href="@Url.Action("Index", "Aterro", new { area = "Configuracao", id = Model[i].AterroID })">
                        <div class="btn btn-primary btn-xs"><i class="fa fa-edit "></i></div>
                    </a>

                </td>
            </tr>
        }
    </tbody>
</table>



<script>

    $(document).ready(function () {
        $('#example').dataTable({
            "lengthChange": false
        });
    });
</script>

Simir.WebInterfaceComAuth/Areas/Configuracao/Views/Aterro/Index.cshtml
@model Simir.Application.ViewModels.AterroVM
@using Simir.Domain.Enuns
@using Simir.WebInterfaceComAuth.Helpers

@{
    ViewBag.Title = "Cadastro de Aterro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.AterroID)
    @Html.HiddenFor(x => x.PrefeituraID)
    @Html.HiddenFor(x => x.Btn)

    <div class="panel panel-default">
        <div class="panel-heading">
            Cadastro de Aterros
        </div>
        <div class="panel-body">
            <div class="col-md-6">
                @Html.ValidationSummary(false, "(* campos obrigatórios)", new { @class = "text-danger" })
                <div class="row" style="margin-left:-3%">
                    <div class="col-md-11"style="margin-left:-3%">
                        @Html.EditBootstrapFor(model => model.nmRazaoSocialAterro, tudoTamanho: 12, inputTamanho: 12)
                    </div>
                    <div class="col-md-1" style="Margin-top:4%;margin-left:-8%;">
                        <div class="btn btn-success" onclick="CarregaGrid();" data-toggle="modal" data-target="#BuscaProgramacao">Localizar</div>
                    </div>
                </div>

                <div class="row">
                    @Html.EditBootstrapFor(model => model.nmFantasiaAterro)
                </div>
                <div class="row">
                    @Html.EditBootstrapFor(model => model.CNPJ)
                </div>
                <div class="row">
                    @Html.EditBootstrapFor(model => model.numeroLicencaOp)
                </div>

                <div class="form-group">
                    <label>@Html.DisplayNameFor(model => model.bAterroControlado)</label>
                    <div class="input-group">
                        <label class="switch">
                            <input checked="checked" class="switch-input" data-val="true" data-val-required="The Unidade de medida field is required."
                                   id="Sim" name="bAterroControlado" type="radio" value="true">
                            <label for="Sim" class="switch-label switch-label-off">Sim</label>

                            <input class="switch-input" id="Nao" name="bAterroControlado" type="radio" value="false">
                            <label for="Nao" class="switch-label switch-label-on">Não</label>
                            <span class="switch-selection"></span>
                        </label>
                    </div>
                </div>

            </div>
            <div class="col-md-6">
                @Html.EditorFor(x => x.Endereco)
            </div>
            <div class="row">
                <div class="modal fade" id="BuscaProgramacao" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                            </div>
                            <div id="modal">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group  pull-right">
                    @if (User.Identity.TemPermicao(TipoPermissao.Incluir) || User.Identity.TemPermicao(TipoPermissao.Alterar))
                {
                        <div class="btn btn-default" onclick=" Novo(); ">Novo</div>
                                <div class="btn btn-success" onclick=" Salvar(); " data-confirm="Tem certeza que deseja salvar?">Salvar</div>
                    }
                    @if (User.Identity.TemPermicao(TipoPermissao.Excluir))
                {
                        <div id="btnExcluir" class="btn btn-danger" onclick=" Excluir(); " data-confirm="Tem certeza que deseja excluir?">Excluir</div>
                    }
                </div>
            </div>
        </div>
    </div>
}

@section Scripts
        {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        function carregaPagina() {
            if ($('#AterroID').val() == 0) {
                $("#btnExcluir").hide();
            }
            $("#bAterroControlado").val(true)
        }

        $(window).load(carregaPagina());

        function Salvar() {
            var form = $('form', '#page-inner');
            if (form.validate()) {
                $('#Btn').val("Salvar");
                form.submit();
                // return true;
            }
        }
        function Novo() {

            var form = $('form', '#page-inner');
            if (form.validate()) {
                $('#Btn').val("Novo");
                form.submit();
                // return true;
            }
        }

        function Excluir() {
            var form = $('form', '#page-inner');
            $('#Btn').val("Excluir");

            //$.desabilitaValidacao();
            $("[data-val='true']").attr('data-val', 'false');

            //Reset validation message
            $('.field-validation-error')
            .removeClass('field-validation-error')
            .addClass('field-validation-valid');

            //Reset input, select and textarea style
            $('.input-validation-error')
            .removeClass('input-validation-error')
            .addClass('valid');

            //Reset validation summary
            $(".validation-summary-errors")
            .removeClass("validation-summary-errors")
            .addClass("validation-summary-valid");

            //To reenable lazy validation (no validation until you submit the form)
            $('form').removeData('unobtrusiveValidation');
            $('form').removeData('validator');
            $.validator.unobtrusive.parse($('form'));

            form.submit();

        }

        $("#Sim").change(function () {
            $("#bAterroControlado").val(true)
        });
        $("#Nao").change(function () {
            $("#bAterroControlado").val(false)
        });

        function CarregaGrid() {
            $("#modal").load("/Configuracao/Aterro/BuscaProgramacao/");
        }

    </script>
}